varselTekst flyttet til FeilutbetaltePerioder klassen, endret fagsystem til ytelsestype og brukte enum. La til validering i språkkode.
navikt/familie-kontrakter pull request #272
Opened 2021-01-26 16:04 UTC by haldersaikat

2021-01-26 19:25 UTC, hensol requested changes
Ser bra ut dette, har bare noen små kommentarer til varseltekst og ytelsestypeEnumen

2021-01-26 19:25 UTC, hensol commented on felles/src/main/kotlin/no/nav/familie/kontrakter/felles/tilbakekreving/Ytelsestype.kt
> +enum class Ytelsestype {
kan vi legge inn en beskrivelse av hva de forskjellige ytelsestypene er? Gjerne som ett eget felt i enumen.

2021-01-26 19:25 UTC, hensol commented on felles/src/main/kotlin/no/nav/familie/kontrakter/felles/tilbakekreving/OpprettTilbakekrevingRequest.kt
> -                                        val varselTekst: String,
Hvor skal varslteksten ligge?

2021-01-27 06:25 UTC, S150405 commented on felles/src/main/kotlin/no/nav/familie/kontrakter/felles/tilbakekreving/OpprettTilbakekrevingRequest.kt
> -                                        val varselTekst: String,
Varselteksten skal inni et objekt som omhandler hele varslet. Akkurat nå heter det objektet FeilutbetaltePerioder men jeg syns det bør endre navn til noe relatert til varsel.

2021-01-27 06:25 UTC, S150405 commented on felles/src/main/kotlin/no/nav/familie/kontrakter/felles/tilbakekreving/FeilutbetaltePerioder.kt
> -data class FeilutbetaltePerioder(val sumFeilutbetaling: BigDecimal,
Syns dette objektet burde hele noe ala Varsel

2021-01-27 07:52 UTC, grmoen-nav commented on felles/src/main/kotlin/no/nav/familie/kontrakter/felles/tilbakekreving/OpprettTilbakekrevingRequest.kt
> +data class OpprettTilbakekrevingRequest(val ytelsestype: Ytelsestype,
Eg meiner me bør ha både fagsystem og ytelsetype. Kanskje til og med ein Enum?

2021-01-27 08:16 UTC, haldersaikat commented on felles/src/main/kotlin/no/nav/familie/kontrakter/felles/tilbakekreving/OpprettTilbakekrevingRequest.kt
> +data class OpprettTilbakekrevingRequest(val ytelsestype: Ytelsestype,
Fagsystem bestemmer vi fra ytelsestype i familie-tilbake. Vi trenger ikke å akseptere begge verdier, synes jeg

2021-01-27 09:09 UTC, haldersaikat commented on felles/src/main/kotlin/no/nav/familie/kontrakter/felles/tilbakekreving/Ytelsestype.kt
> +enum class Ytelsestype {
la til beskrivelse

2021-01-27 09:09 UTC, haldersaikat commented on felles/src/main/kotlin/no/nav/familie/kontrakter/felles/tilbakekreving/OpprettTilbakekrevingRequest.kt
> -                                        val varselTekst: String,
endret navn til varsel

2021-01-27 09:09 UTC, haldersaikat commented on felles/src/main/kotlin/no/nav/familie/kontrakter/felles/tilbakekreving/FeilutbetaltePerioder.kt
> -data class FeilutbetaltePerioder(val sumFeilutbetaling: BigDecimal,
endret

2021-01-27 09:23 UTC, hensol approved these changes
Hadde bare en liten kommentar, ellers er det bare å merge når den er rettet.

2021-01-27 09:23 UTC, hensol commented on felles/src/main/kotlin/no/nav/familie/kontrakter/felles/tilbakekreving/Ytelsestype.kt
> +    OG("OVERGANGSSTØNAD"),
småplukk men fint om vi gjør om  BARNETILSYN -> Barnetilsyn og OVERGANGSSTØNAD -> Overgangsstønad

2021-01-27 09:25 UTC, haldersaikat commented on felles/src/main/kotlin/no/nav/familie/kontrakter/felles/tilbakekreving/Ytelsestype.kt
> +    OG("OVERGANGSSTØNAD"),
fikset. Det skjedde p.g.a kopiering

2021-01-27 09:29 UTC, S150405 approved these changes

2021-01-27 09:46 UTC, merged